//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_square_H
#define METASPRITE_square_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define square_TILE_ORIGIN 0
#define square_TILE_W 8
#define square_TILE_H 8
#define square_WIDTH 8
#define square_HEIGHT 8
#define square_TILE_COUNT 1
#define square_PALETTE_COUNT 1
#define square_COLORS_PER_PALETTE 4
#define square_TOTAL_COLORS 4
#define square_MAP_ATTRIBUTES 0

BANKREF_EXTERN(square)

extern const palette_color_t square_palettes[4];
extern const uint8_t square_tiles[368];
extern const uint8_t black_tile[16];
extern const uint8_t white_tile[16];
extern const uint8_t x_tile[16];
extern const unsigned char square_map[361];
extern const unsigned char black_piece_map[1];
extern const unsigned char white_piece_map[1];
extern const unsigned char nine_vertical[9];
extern const unsigned char nine_horizontal[8];
extern const unsigned char thirteen_vertical[13];
extern const unsigned char thirteen_horizontal[12];
extern const unsigned char fixed_vertical[13];
extern const unsigned char fixed_horizontal[12];
extern const unsigned char empty[190];
extern const unsigned char normal[1];
extern const unsigned char special[1];
#define square_map_attributes square_map

#endif
